model_type: RetargetingNN
output_units: rad
state_dict_path: retargeting_nn_dex3_1_hand_dexpilot_63d.pth
mano_dim: 63
robot_dim: 7
hidden_dim: 512
hidden_layers: 3
dataset_path: mano/outputs/dex3_1_dexpilot_retargeted_63d.npz
dataset_sha256: 6c77c61f464493700da94e1580b0cc84f59af30132a29fe86742c73de94c7110
input_key: mano_pose_63
target_key: dex3_1_qpos
sample_count: 159241
input_dim: 63
robot_joint_names:
- right_hand_thumb_0_joint
- right_hand_thumb_1_joint
- right_hand_thumb_2_joint
- right_hand_index_0_joint
- right_hand_index_1_joint
- right_hand_middle_0_joint
- right_hand_middle_1_joint
target_joint_names:
- right_hand_thumb_0_joint
- right_hand_thumb_1_joint
- right_hand_thumb_2_joint
- right_hand_index_0_joint
- right_hand_index_1_joint
- right_hand_middle_0_joint
- right_hand_middle_1_joint
epochs: 100
batch_size: 1024
learning_rate: 0.001
weight_decay: 1e-05
val_fraction: 0.09999937202102474
train_count: 143317
val_count: 15924
seed: 42
split_mode: random
best_epoch: 99
train_mse: 0.007900950657230501
train_mae: 0.05334774278023154
val_mse: 0.007602019746186849
val_mae: 0.05089018076164164
